<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Motiurs-MBP.fios-router.home" name="home.HomeTest" tests="6" failures="1" timestamp="2022-11-17T02:00:59 EST" time="0.049" errors="0">
  <testcase name="aHomeTest" time="0.039" classname="home.HomeTest"/>
  <system-out>
    <![CDATA[No priority 5<br>]]>
  </system-out>
  <testcase name="homeQuote4" time="0.003" classname="home.HomeTest">
    <skipped/>
  </testcase> <!-- homeQuote4 -->
  <system-out>
    <![CDATA[No priority 4<br>
Retrying ... 2<br>]]>
  </system-out>
  <testcase name="homeQuote4" time="0.001" classname="home.HomeTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at home.HomeTest.homeQuote4(HomeTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- homeQuote4 -->
  <system-out>
    <![CDATA[No priority 4<br>]]>
  </system-out>
  <testcase name="homeQuote4" time="0.006" classname="home.HomeTest">
    <skipped/>
  </testcase> <!-- homeQuote4 -->
  <system-out>
    <![CDATA[No priority 4<br>
Retrying ... 1<br>]]>
  </system-out>
  <testcase name="homeQuote3" classname="home.HomeTest">
    <skipped/>
  </testcase> <!-- homeQuote3 -->
  <system-out/>
  <testcase name="bHomeTest" classname="home.HomeTest">
    <skipped/>
  </testcase> <!-- bHomeTest -->
  <system-out/>
</testsuite> <!-- home.HomeTest -->
